input_video_path: "C:\\Users\\busen\\Tectwin\\object_tracking_challenge\\videos\\20240318_092055.mp4" # videos/20240318_092055.mp4
output_video_path: output/detected.mp4
task_type: "object_tracking" # "object_detection", "object_tracking", "speed_estimation"
model_name: yolov8m.pt # yolov8s.pt, yolov8n.pt
scale: 100 